name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'
    
    - name: Build and package binaries
      run: |
        # Linux amd64
        GOOS=linux GOARCH=amd64 go build -o lyn ./...
        tar -czf lyn-linux-amd64.tar.gz lyn
        rm lyn
        
        # Linux arm64
        GOOS=linux GOARCH=arm64 go build -o lyn ./...
        tar -czf lyn-linux-arm64.tar.gz lyn
        rm lyn
        
        # Windows amd64
        GOOS=windows GOARCH=amd64 go build -o lyn.exe ./...
        zip lyn-windows-amd64.zip lyn.exe
        rm lyn.exe
        
        # macOS amd64
        GOOS=darwin GOARCH=amd64 go build -o lyn ./...
        tar -czf lyn-darwin-amd64.tar.gz lyn
        rm lyn
        
        # macOS arm64 (Apple Silicon)
        GOOS=darwin GOARCH=arm64 go build -o lyn ./...
        tar -czf lyn-darwin-arm64.tar.gz lyn
        rm lyn
    
    - name: Create/Update Unstable Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: unstable
        name: Unstable Build
        prerelease: true
        files: |
          lyn-linux-amd64.tar.gz
          lyn-linux-arm64.tar.gz
          lyn-windows-amd64.zip
          lyn-darwin-amd64.tar.gz
          lyn-darwin-arm64.tar.gz
        body: |
          Automated nightly build from the main branch.
          
          **Commit:** ${{ github.sha }}
          **Date:** ${{ github.event.head_commit.timestamp }}
